config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates  :nombre, :ciudad, length: {maximum: 50 }
  validates  :departamento, :correo,  length: {maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    url = "https://sigma-studios.s3-us-west-2.amazonaws.com/test/colombia.json"
    response = Faraday.get url
    p response.body


  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Tu información ha sido recibida satisfactoriamente.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:nombre, :correo, :departamento, :ciudad)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @contact = Contact.new


  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: @contact, local: true) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this @contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form>

    <div class="col">
      <label class="left tituloLanding" for="exampleFormControlSelect1">Departamento*</label>
      <select class="form-control" id="exampleFormControlSelect1">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
      </select>
    </div>

    <div class="col">
      <label class="left tituloLanding" for="exampleFormControlSelect1">Ciudad*</label>
      <select class="form-control" id="exampleFormControlSelect1">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
      </select>
    </div>


    <br>

      <div class="col">
        <%= form.label "Nombre*",  class:"left tituloLanding" %>
        <%= form.text_field :nombre, class:"form-control" ,placeholder:"Pepito de Jesús" %>
      </div>
      <br>

      <div class="col">
        <%= form.label "Correo*",  class:"left tituloLanding" %>
        <%= form.text_field :correo , class:"form-control" ,placeholder:"Pepitodejesus@gmail.com" , type:"email"%>

      </div>


      <br>

      <div class="actions">
        <%= form.submit "Enviar",  class:"btn btn-lg rounded fondoRosa"%>
      </div>




    </form>




<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Departamento</th>
      <th>Ciudad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.nombre %></td>
        <td><%= contact.correo %></td>
        <td><%= contact.departamento %></td>
        <td><%= contact.ciudad %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @contact.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @contact.correo %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @contact.departamento %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @contact.ciudad %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sigma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;500&display=swap" rel="stylesheet">



  </head>

  <body>
    <%= render "partials/notificaciones.html"%>
    <%= yield %>
  </body>
</html>

app/views/partials/_notificaciones.html.erb
<div class="container center">
<% unless notice.nil? %>
  <div class="col-md-12">
    <div class="alert alert-success alert-dismissible fade show my-3" role="alert">  <strong>Mensaje:
      <button aria-label="Close" class="close" data-dismiss="alert" type="button">

        <span aria-hidden="true">X</span>
      </button>
    </strong>
        <%= notice %></div>
  </div>


<% end %>
<% unless alert.nil? %>
  <div class="col-md-12">
    <div class="alert alert-warning alert-dismissible fade show my-3" role="alert">
      <strong>Alerta</strong>
      <%= alert %>
      <button aria-label="Close" class="close" data-dismiss="alert" type="button">
        <span aria-hidden="true">X</span>
      </button>
    </div>
  </div>

<% end %>
  </div>

app/views/welcome/index.html.erb
<br>

<div class="container h-100">
     <div class="row justify-content-center h-100">
         <div class="col align-self-center text-center">
           <img src="/image/sigma-logo.png/" class="justify-content-center">
                <br>
                <br>
           <h3 class="tituloLanding">Prueba de desarrollo Sigma</h3>
           <br>
           <p>Lorem ipsum is simply dummy text of the printing and typesetting industry. Lorem ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galler of type and scrambled it to make a type specimen book.</p>
         </div>
     </div>
                <br>
                <br>

     <div class="row justify-content-center ">
         <div class="col-12 col-sm-6  align-self-center text-center columna">
           <img src="/image/sigma-image.png/" class="imagenLanding">

         </div>


         <div class="col-12 col-sm-6  align-self-center text-center columna">

           <div class="card rounded shadow p-3 mb-5 bg-white rounded">

              <div class="card-body">

                  <%= render "contacts/form", contact: @contact %>

              </div>

            </div>

         </div>

     </div>


 </div>